In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.22.4 in c:\users\angel\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\angel\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\angel\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\angel\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\angel\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.3/11.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.3 MB 1.9 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/11.3 MB 2.1 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/11.3 MB 2.1 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/11.3 MB 1.2 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/11.3 MB 1.2 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/11.3 MB 1.2 MB/s eta 0:00:09
   ------ --------------------------------- 1.8/11.3 MB 1.1 MB/s eta 0:00:09
   -------- ------------------------------- 2.4/11.3 MB 1.2 MB/s eta 0:00:08
   -------- ------------------------------- 2.4/11.3 MB 1.2 MB/s eta 0:00:08
   ----------- ---------------------------- 3.1/11.3 MB 1.3 MB/s eta 0:00:07
   ------------ --------------------------- 3.4/11.3 MB 1.4 MB/s eta 0:00:06
   -------------- ------------------------- 4.2/11.3 MB 1.5 MB/s eta 0:00:05
   ---------------- ----------------------- 4.7/11.3 MB 1.6 MB/s eta 0:00:05
   ------------------ --------------------- 5.2/11.3 MB 1.7 MB/s eta 0:00:04
   ------------------- -------------------- 5.5/11.3 MB 1.7 MB/s eta 0:00:04
   -------------------- ------------------- 5.8/11.3 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.8/11.3 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.8/11.3 MB 1.6 MB/s eta 0:00:04
   --------------------- ------------------ 6.0/11.3 MB 1.4 MB/s eta 0:00:04
   --------------------- ------------------ 6.0/11.3 MB 1.4 MB/s eta 0:00:04
   ---------------------- ----------------- 6.3/11.3 MB 1.3 MB/s eta 0:00:04
   ---------------------- ----------------- 6.3/11.3 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 6.6/11.3 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 6.6/11.3 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 6.6/11.3 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 6.6/11.3 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 6.6/11.3 MB 1.3 MB/s eta 0:00:04
   ------------------------ --------------- 6.8/11.3 MB 1.1 MB/s eta 0:00:05
   ------------------------ --------------- 6.8/11.3 MB 1.1 MB/s eta 0:00:05
   ------------------------ --------------- 7.1/11.3 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 7.1/11.3 MB 1.1 MB/s eta 0:00:04
   ------------------------- -------------- 7.3/11.3 MB 1.1 MB/s eta 0:00:04
   ------------------------- -------------- 7.3/11.3 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 7.6/11.3 MB 1.0 MB/s eta 0:00:04
   -------------------------- ------------- 7.6/11.3 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 7.9/11.3 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 7.9/11.3 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 7.9/11.3 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 7.9/11.3 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 7.9/11.3 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 7.9/11.3 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 7.9/11.3 MB 1.0 MB/s eta 0:00:04
   ---------------------------- ----------- 8.1/11.3 MB 866.3 kB/s eta 0:00:04
   ---------------------------- ----------- 8.1/11.3 MB 866.3 kB/s eta 0:00:04
   ---------------------------- ----------- 8.1/11.3 MB 866.3 kB/s eta 0:00:04
   ---------------------------- ----------- 8.1/11.3 MB 866.3 kB/s eta 0:00:04
   ----------------------------- ---------- 8.4/11.3 MB 824.3 kB/s eta 0:00:04
   ----------------------------- ---------- 8.4/11.3 MB 824.3 kB/s eta 0:00:04
   ------------------------------ --------- 8.7/11.3 MB 809.8 kB/s eta 0:00:04
   ------------------------------ --------- 8.7/11.3 MB 809.8 kB/s eta 0:00:04
   ------------------------------ --------- 8.7/11.3 MB 809.8 kB/s eta 0:00:04
   ------------------------------ --------- 8.7/11.3 MB 809.8 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   ------------------------------- -------- 8.9/11.3 MB 780.9 kB/s eta 0:00:04
   -------------------------------- ------- 9.2/11.3 MB 553.3 kB/s eta 0:00:04
   -------------------------------- ------- 9.2/11.3 MB 553.3 kB/s eta 0:00:04
   --------------------------------- ------ 9.4/11.3 MB 551.4 kB/s eta 0:00:04
   --------------------------------- ------ 9.4/11.3 MB 551.4 kB/s eta 0:00:04
   --------------------------------- ------ 9.4/11.3 MB 551.4 kB/s eta 0:00:04
   --------------------------------- ------ 9.4/11.3 MB 551.4 kB/s eta 0:00:04
   --------------------------------- ------ 9.4/11.3 MB 551.4 kB/s eta 0:00:04
   --------------------------------- ------ 9.4/11.3 MB 551.4 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 526.1 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 526.1 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 526.1 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 526.1 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 526.1 kB/s eta 0:00:04
   ----------------------------------- ---- 10.0/11.3 MB 513.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 513.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 513.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 513.9 kB/s eta 0:00:03
   ------------------------------------ --- 10.2/11.3 MB 504.0 kB/s eta 0:00:03
   ------------------------------------ --- 10.2/11.3 MB 504.0 kB/s eta 0:00:03
   ------------------------------------ --- 10.2/11.3 MB 504.0 kB/s eta 0:00:03
   ------------------------------------ --- 10.2/11.3 MB 504.0 kB/s eta 0:00:03
   ------------------------------------ --- 10.5/11.3 MB 498.0 kB/s eta 0:00:02
   ------------------------------------ --- 10.5/11.3 MB 498.0 kB/s eta 0:00:02
   ------------------------------------- -- 10.7/11.3 MB 499.7 kB/s eta 0:00:02
   ---------------------------------------  11.3/11.3 MB 516.6 kB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 515.1 kB/s eta 0:00:00
Installing collected packages: pandas
Successfully installed pandas-2.3.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
data={'Name':['Alice','Bob'],'Age':[25,30]}

In [5]:
df=pd.DataFrame(data)

In [12]:
lst= [['Alice',25],['Bob',30]]

In [14]:
df=pd.DataFrame(lst,columns=['Name','Age'])

In [15]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [16]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes

In [18]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [19]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: object

In [20]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [21]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [22]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [24]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [25]:
df['Gender']=['F','M']

In [26]:
df.drop('Age',axis=1,inplace=True)

In [27]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [28]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [29]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [34]:
df['Age']=[25,30]

In [35]:
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [33]:
print(df.columns)

Index(['Name', 'Gender'], dtype='object')

In [39]:
import pandas as pd

df1 = pd.DataFrame({
    'key': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'key': [1, 2, 3],
    'Age': [25, 30, 35]
})

result = pd.merge(df1, df2, on='key')
print(result)

   key     Name  Age
0    1    Alice   25
1    2      Bob   30
2    3  Charlie   35

In [40]:
pd.merge(df1,df2,on='key')

   key     Name  Age
0    1    Alice   25
1    2      Bob   30
2    3  Charlie   35

In [44]:
df1.join(df2, lsuffix='_left',rsuffix='_right')

   key_left     Name  key_right  Age
0         1    Alice          1   25
1         2      Bob          2   30
2         3  Charlie          3   35

In [56]:
df=pd.read_csv("C:/Users/angel/OneDrive/Documents/datass.csv")

In [58]:
df.to_csv('output.csv',index=False)

In [59]:
df.sort_values('Age')

      Name  Age gender
3      anu   20      f
4     abhi   21      m
0    alice   25      f
1      bob   30      m
2  charlie   35      m

In [60]:
df['Age'].apply(lambda x:x+1)

0    26
1    31
2    36
3    21
4    22
Name: Age, dtype: int64

In [62]:
df['Name'].unique()

array(['alice', 'bob', 'charlie', 'anu', 'abhi'], dtype=object)

In [63]:
df['Age'].value_counts()

Age
25    1
30    1
35    1
20    1
21    1
Name: count, dtype: int64